#-------------------------------------------------------------------------------
# Configs for debugging and restoring the preprocess compilation options.
#
# pycparser supports the full C99 language, some features from C11, 
# and very few GCC extensions.
#
# For something outside the C runtime (standard library), 
# e.g., system lib., third party lib., their definitions should be given 
# explicitly with compilation options.
#
# Some useful cpp_args:
#   -nostdinc: block gcc pre-set system header directories, forcing it only 
#              looks in the directories explicitly specified with -I
#   -std=c99: prevent gcc from taking C for C++ for some reasons
#   -D__attribute__(x)=: #define GNU-specifics
#     -D<macro>=<value>  Define <macro> to <value> (or 1 if <value> omitted)
#   -I/YOUR_PATH/llvm-project/lldb/include/lldb/Host/windows/:
#     path for cross compiling Windows (windows.h and other headers), 
#     use extra_fake_libc_include/windows.h instead
#-------------------------------------------------------------------------------
all:
 - -E
 - -std=c99
 - -D__attribute__(x)=
 - -D__extension__=
 - -I/home/dingqiuran/pycparser/pycparser/utils/fake_libc_include
# - -I/usr/include/python3.12
 - -m64

# fake headers from pycparser: https://github.com/eliben/pycparser

ldap:
 - -I/home/dingqiuran/test/cpython/Include
 - -I/home/dingqiuran/test/cpython
 - -DHAVE_SASL
 - -DHAVE_TLS
 - -DLDAP_API_FEATURE_CANCEL
 - -D__OSX_AVAILABLE_BUT_DEPRECATED_MSG(...)=

python314:
 - -I/home/dingqiuran/test/cpython/Include
 - -I/home/dingqiuran/test/cpython
 - -I/home/dingqiuran/test/cpython/Include/cpython
 - -I/home/dingqiuran/test/cpython/Include/internal
 - -I/home/dingqiuran/test/cpython/Include/internal/mimalloc
 - -I/home/dingqiuran/test/cpython/Include/internal/mimalloc/mimalloc
 - -I./extra_fake_libc_include
 - -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
 - -I/usr/local/Cellar/openssl@1.1/1.1.1k/include
 - -DPy_BUILD_CORE=1
 - -DPREFIX
 - -DEXEC_PREFIX
 - -DVPATH
 - -D__signed=signed
 - -D__inline__=
 - -D__inline=inline
 - -D_Py_atomic_int=int
 - -Dspeed_t=int
 - -Dtcflag_t=int
 - -Dcc_t=int
 - -DHAVE_NDBM_H
 - -DDBM=int
 - -D_POSIX_THREADS
 - -Dsocklen_t=int
 - -Dquad_t=int
 - -Du_quad_t=int
 - -Dfd_set=int
 - -DXSetWindowAttributes=int
 - -DXErrorEvent=int
 - -DFont=int
 - -I/usr/local/Cellar/libffi/3.3_3/include
 - -DLIBFFI_HIDE_BASIC_TYPES
 - -DSHRT_MAX=32767
 - -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi
 - -DCONFIG_64
 - -DFLT_RADIX=2
 - -D__OSX_AVAILABLE_STARTING=
 - -DKeccakOpt=64
 - -DMODULE_NAME=
 - -D__int128_t=int
 - -D__uint128_t=int
 - -D__v4sf=int
 - -D__v2df=int
 - -D__m64=int
 - -D__m128i=int
 - -D__v2si=int
 - -D__v4hi=int
 - -D__v4si=int
 - -D__v8qi=int
 - -D__v8hi=int
 - -D__v16qi=int
 - -DLEGACY_COMPILER
 - -DUINT64_MAX
#  - -D__asm__=_asm

numpy:
 - -I/home/dingqiuran/test/cpython/Include
 - -I/home/dingqiuran/test/cpython
 - -I./extra_fake_libc_include
 - -I/home/dingqiuran/test/numpy/numpy/_core/include
 - -I/home/dingqiuran/test/numpy/numpy/_core/include/numpy
 - -I/home/dingqiuran/test/numpy/numpy/_core/src/multiarray
 - -I/home/dingqiuran/test/numpy/numpy/_core/srccommon
 - -I/home/dingqiuran/test/numpy/numpy/_core/src/umath
 - -I/home/dingqiuran/test/numpy/numpy/f2py/src
 - -I/home/dingqiuran/test/numpy/numpy/random/include
 - -I/home/dingqiuran/test/numpy/numpy/random
 - -I/home/dingqiuran/test/numpy/numpy/_core/src/common/
 - -I/home/dingqiuran/anaconda3/lib/python3.12/site-packages/numpy/core/include/numpy
 - -I/usr/local/lib/clang/16/include/
 - -I/home/dingqiuran/test/numpy/build/numpy/_core/
 - -I/home/dingqiuran/test/numpy/numpy/_core/src/common/pythoncapi-compat/
 - -I/home/dingqiuran/test/numpy/build/meson_cpu/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/failing/62 subproj different versions/subprojects/a/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/common/122 no buildincdir/include/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/unit/65 static archive stripping/lib/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/common/80 declare dep/entity/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/swift/5 mixed/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/common/233 wrap case/subprojects/up_down/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/common/138 C and CPP link/
 - -I/home/dingqiuran/test/numpy/vendored-meson/meson/test cases/failing/122 override and add_project_dependency/inc/
 - -I/usr/include/lua5.3/
 - -I/usr/include/sqlite3
 - -Dnpy_uint8=unsigned int
 - -Dnpy_uint16=unsigned int
 - -Dnpy_uint32=unsigned int
 - -Dnpy_uint64=unsigned long
 - -Dnpy_int8=int
 - -Dnpy_int16=int
 - -Dnpy_int32=int
 - -Dnpy_int64=long
 - -Dnpy_ucs4=unsigned long
 - -DNPY_INT32_FMT="hhd"
 - -DNPY_INT64_FMT="hhd"
 - -Dnpy_float32=float
 - -Dnpy_float64=float
 - -D__inline__=
 - -DPyArray_BinSearchFunc=int
 - -DPyArray_ArgBinSearchFunc=int
 - -D__uint128_t=int
#  - -DCHAR_BIT=8

pillow:
 - -I/home/dingqiuran/test/cpython/Include
 - -I/home/dingqiuran/test/cpython
 - -I/home/dingqiuran/test/Pillow/src/libImaging
 - -I/home/dingqiuran/test/Pillow/src/Tk
 - -I/usr/include/freetype2
 - -I/usr/include/harfbuzz
 - -DCHAR_BIT=8
